# Generated by Django 4.2.6 on 2024-01-10 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_order_customer_purchase'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Purchase',
        ),
    ]
