# Generated by Django 4.2.6 on 2024-01-12 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='shipping_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.shippingaddress'),
        ),
    ]
